// Generated by jextract

package trie.asm;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

class constants$0 {

	static final FunctionDescriptor find_rel$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
			Constants$root.C_LONG_LONG$LAYOUT,
			Constants$root.C_LONG_LONG$LAYOUT,
			Constants$root.C_LONG_LONG$LAYOUT,
			Constants$root.C_LONG_LONG$LAYOUT,
			Constants$root.C_LONG_LONG$LAYOUT);
	static final MethodHandle find_rel$MH = RuntimeHelper.downcallHandle(
			"find_rel",
			constants$0.find_rel$FUNC, false);
	static final FunctionDescriptor find_abs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
			Constants$root.C_LONG_LONG$LAYOUT,
			Constants$root.C_LONG_LONG$LAYOUT,
			Constants$root.C_INT$LAYOUT);
	static final MethodHandle find_abs$MH = RuntimeHelper.downcallHandle(
			"find_abs",
			constants$0.find_abs$FUNC, false);
	static final FunctionDescriptor noop$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
			Constants$root.C_LONG_LONG$LAYOUT,
			Constants$root.C_LONG_LONG$LAYOUT,
			Constants$root.C_INT$LAYOUT);
	static final MethodHandle noop$MH = RuntimeHelper.downcallHandle(
			"noop",
			constants$0.noop$FUNC, false);
}
